name: Build & Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.3.0']

    steps:
      - uses: actions/checkout@v4

      - name: Go to project folder
        run: cd FAQ-component

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Run npm build
        run: npm run build:prod

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}y_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
